#!/bin/bash

argc=$#

if [ "$argc" = 0 ]; then
    ./program/run --help
fi

for i in "$@"; do
	if [ "$i" = "compile" ]; then

		make -C program/ clean
        make -C program/
        clear
        echo "Bitchain Compiled"
    elif [ "$i" = "version" ]; then
        ./program/run --version 
    elif [ "$i" = "help" ] || [ "$i" = "usage" ]; then
        ./program/run --help 
	fi
done
